[2015-09-29 07:07:20] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\AuthController does not exist' in C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\ControllerInspector.php:28
Stack trace:
#0 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\ControllerInspector.php(28): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(251): Illuminate\Routing\ControllerInspector->getRoutable('App\\Http\\Contro...', 'auth')
#2 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(213): Illuminate\Routing\Router->controller('auth', 'AuthController')
#3 C:\xampp\htdocs\lublog\app\Http\routes.php(19): Illuminate\Support\Facades\Facade::__callStatic('controller', Array)
#4 C:\xampp\htdocs\lublog\app\Http\routes.php(19): Illuminate\Support\Facades\Route::controller('auth', 'AuthController')
#5 C:\xampp\htdocs\lublog\app\Providers\RouteServiceProvider.php(40): require('C:\\xampp\\htdocs...')
#6 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(343): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#8 C:\xampp\htdocs\lublog\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group(Array, Object(Closure))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Container\Container.php(523): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\lublog\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Container\Container.php(523): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(672): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(654): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 18)
#19 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(655): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(167): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(191): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(88): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\lublog\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2015-09-29 07:11:27] local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\AuthController does not exist' in C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\ControllerInspector.php:28
Stack trace:
#0 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\ControllerInspector.php(28): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(251): Illuminate\Routing\ControllerInspector->getRoutable('App\\Http\\Contro...', 'auth')
#2 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(213): Illuminate\Routing\Router->controller('auth', 'AuthController')
#3 C:\xampp\htdocs\lublog\app\Http\routes.php(19): Illuminate\Support\Facades\Facade::__callStatic('controller', Array)
#4 C:\xampp\htdocs\lublog\app\Http\routes.php(19): Illuminate\Support\Facades\Route::controller('auth', 'AuthController')
#5 C:\xampp\htdocs\lublog\app\Providers\RouteServiceProvider.php(40): require('C:\\xampp\\htdocs...')
#6 [internal function]: App\Providers\RouteServiceProvider->App\Providers\{closure}(Object(Illuminate\Routing\Router))
#7 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(343): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#8 C:\xampp\htdocs\lublog\app\Providers\RouteServiceProvider.php(41): Illuminate\Routing\Router->group(Array, Object(Closure))
#9 [internal function]: App\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#10 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Container\Container.php(523): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(68): Illuminate\Container\Container->call(Array)
#12 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#13 C:\xampp\htdocs\lublog\app\Providers\RouteServiceProvider.php(25): Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#14 [internal function]: App\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#15 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Container\Container.php(523): call_user_func_array(Array, Array)
#16 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(672): Illuminate\Container\Container->call(Array)
#17 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(654): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RouteServiceProvider))
#18 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RouteServiceProvider), 18)
#19 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(655): array_walk(Array, Object(Closure))
#20 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#21 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(167): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#22 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(191): Illuminate\Foundation\Application->bootstrapWith(Array)
#23 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(88): Illuminate\Foundation\Console\Kernel->bootstrap()
#24 C:\xampp\htdocs\lublog\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}  
[2015-09-29 07:42:08] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '">=>登陆到后台</a>' (T_CONSTANT_ENCAPSED_STRING)' in C:\xampp\htdocs\lublog\storage\framework\views\06c5ba20a000b0fe1db9381ad8d74cab:229
Stack trace:
#0 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(131): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(57): Illuminate\View\Engines\PhpEngine->evaluatePath()
#4 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\View\View.php(136): Illuminate\View\Engines\CompilerEngine->get()
#5 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\View\View.php(104): Illuminate\View\View->getContents()
#6 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\View\View.php(78): Illuminate\View\View->renderContents()
#7 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Http\Response.php(44): Illuminate\View\View->render()
#8 C:\xampp\htdocs\lublog\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Illuminate\Http\Response->setContent()
#9 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1188): Symfony\Component\HttpFoundation\Response->__construct()
#10 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(692): Illuminate\Routing\Router->prepareResponse()
#11 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func:{C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:141}()
#13 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func:{C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:101}()
#15 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(693): Illuminate\Pipeline\Pipeline->then()
#16 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(660): Illuminate\Routing\Router->runRouteWithinStack()
#17 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Routing\Router.php(618): Illuminate\Routing\Router->dispatchToRoute()
#18 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(210): Illuminate\Routing\Router->dispatch()
#19 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#20 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func:{C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:141}()
#21 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 C:\xampp\htdocs\lublog\app\Http\Middleware\VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#23 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle()
#24 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#26 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle()
#28 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#30 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#32 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#34 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func:{C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:101}()
#36 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Pipeline\Pipeline->then()
#37 C:\xampp\htdocs\lublog\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#38 C:\xampp\htdocs\lublog\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#39 C:\xampp\htdocs\lublog\public\index.php(0): {main}()
#40 {main}  
